variable "pip-name" {}
variable "pip-allocation_method" {}
variable "LB-name" {}
variable "LB-FEIP-name" {}
variable "BEPool-name" {}
variable "LBProbe-name" {}
variable "LBprobe-port" {}
variable "LBRule-name" {}
variable "LBRule-protocol" {}
variable "LBRule-frontend-port" {}
variable "LBRule-backend-port" {}
variable "NSG-name" {}
variable "NSR-name" {}
variable "NSR-priority" {}
variable "NSR-direction" {}
variable "NSR-access" {}
variable "NSR-protocol" {}
variable "NSR-source_port_range" {}
variable "NSR-destination_port_range" {}
variable "NSR-source_address_prefix" {}
variable "NSR-destination_address_prefix" {}
variable "resource-group-name" {}
variable "location" {}
