variable "resource-group2-name" {}
variable "location2" {}
variable "TF-PIP-name" {}
variable "TF-PIP-allocation_method" {}
variable "TF-PIP-domain_name_label" {}
variable "TF-Profile-name" {}
variable "TF-Profile-traffic_routing_method" {}
variable "TF-Profile-relative_name" {}
variable "TF-Profile-ttl" {}
variable "TF-Profile-protocol" {}
variable "TF-Profile-port" {}
variable "TF-Profile-path" {}
variable "TF-Profile-interval_in_seconds" {}
variable "TF-Profile-timeout_in_seconds" {}
variable "TF-Profile-tolerated_number_of_failures" {}
variable "TF-endpoint-name" {}
variable "TF-endpoint-weight" {}
