variable "resource-group2-name" {}
variable "vnet2-name" {}
variable "location2" {}
variable "PTS-sb-name" {}
variable "PTS-sb-address_prefixes" {}
variable "PTS-LNGonpremise-name" {}
variable "PTS-LNGonpremise-gateway_address" {}
variable "PTS-LNGonpremise-address_space" {}
variable "PTS-pip-name" {}
variable "PTS-pip-allocation_method" {}
variable "PTS-VNG-name" {}
variable "PTS-VNG-type" {}
variable "PTS-VNG-vpn_type" {}
variable "PTS-VNG-active_active" {}
variable "PTS-VNG-enable_bgp" {}
variable "PTS-VNG-sku" {}
variable "PTS-VNG-ipc-private_ip_address_allocation" {}
variable "PTS-VNGC-name" {}
variable "PTS-VNGC-type" {}
variable "PTS-VNGC-shared_key" {}
